# Generated by Django 6.0.3 on 2026-03-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_donation_user_volunteer_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lives_touched', models.CharField(default='12K+', max_length=20)),
                ('bloom_rate', models.CharField(default='85%', max_length=20)),
                ('communities', models.CharField(default='40+', max_length=20)),
            ],
        ),
    ]
