# Generated by Django 6.0.3 on 2026-04-02 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_projectupdate_project_eventimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#7C9070', help_text='Hex color code for tags (e.g. #D97757)', max_length=20),
        ),
        migrations.AddField(
            model_name='galleryphoto',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.category'),
        ),
        migrations.AddField(
            model_name='galleryphoto',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
