# Generated by Django 6.0.3 on 2026-04-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_donation_status_alter_donation_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='donations/'),
        ),
    ]
